core/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from wedding.views import *
from wedding.api import get_guests_data, GuestsAutoViewSet

router = routers.DefaultRouter()
router.register(r'guestsapi', GuestsAutoViewSet)

urlpatterns = [
    path('api/v1/', include(router.urls)),
    path('api/v1/guests/<str:data>/', get_guests_data)
    ]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('home/', view = wedding_invitation_view, name = "invitation-view"),
    path("", include("wedding.urls")),
]

wedding/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'wedding'

urlpatterns = [
    path('guests-data/', view = views.bride_form_view, name = "bride-form-view"),
    path('guests-table/', view = views.guests_table, name = "guests_table"),
    path('guests-data/save_data/<str:pk>', view = views.update_data, name = "update_data"),
    path('x/', view = views.copy_data, name = "x"),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

wedding/models.py
from django.db import models

# Create your models here.

answer_choices = (("Sí asistiré", "Sí asistiré"), ("No asistiré", "No asistiré"))

class Guests(models.Model):
    '''
    
    '''
    identifier = models.CharField(max_length = 100, blank = False, null = False)
    code = models.CharField(max_length = 6, blank = True, null = True, unique = True)
    num_guests_assigned = models.IntegerField(max_length = 10)
    num_guests_selected = models.CharField(max_length = 50, blank = True, null = True)
    answer = models.CharField(max_length = 100, blank = True, null = True, choices = answer_choices, default = "Pendiente") 
    guests_names = models.CharField(max_length = 800, blank = True, null = True)
    wish_text = models.TextField(blank = True, null = True)
    
    

wedding/forms.py
from django import forms
from . import models

class Guests_bride_form(forms.ModelForm):
    class Meta:
        model = models.Guests
        fields = ['identifier', 'num_guests_assigned']
        
        widgets = {'identifier': forms.TextInput(attrs = {'class': 'input-inv h-18 min-w-[20rem] rounded-lg border-white-500 indent-4 text-white-900 shadow-lg focus:outline-none focus:ring focus:ring-white-600', 'placeholder': 'Ingresar invitado', 'autocomplete': 'off'}),
                    'num_guests_assigned': forms.TextInput(attrs = {'class': 'input-asis h-18 min-w-[20rem] rounded-lg border-white-500 indent-4 text-white-900 shadow-lg focus:outline-none focus:ring focus:ring-white-600', 'placeholder': 'Ingresar cantida de invitados', 'autocomplete': 'off'}),}
        
class Guests_form(forms.ModelForm):
    class Meta:
        model = models.Guests
        fields = ['num_guests_selected', 'answer', 'guests_names', 'wish_text']
        
        
class SearchForm(forms.Form):
    code = forms.CharField(max_length = 6, required = False)
    

wedding/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.template import loader
from . import forms, models

import random

# Create your views here.
def random_code():
    '''
    
    '''
    length_code = 5
    sample = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    code = ''.join(random.choices(sample, k = length_code))
    return str(code)


def bride_form_view(request):
    '''
    
    '''
    if request.method == "GET":
        form = forms.Guests_bride_form() 
    if request.method == "POST":
        form = forms.Guests_bride_form(request.POST)
        if form.is_valid():
            form_instance = form.save()
            form_pk = form_instance.pk
            models.Guests.objects.filter(id = form_pk).update(code = random_code())
            
    return render(request = request, template_name = 'bride_form_template.html', context = {'form':form})


def wedding_invitation_view(request):
    if request.method == "POST":
        id = request.POST.get('id', None)
        asistentes = request.POST.get('asistentes', None)
        invitados = request.POST.get('invitados', None)
        asistencia = request.POST.get('asistencia', None)
        
        instancia = models.Guests.objects.get(id = int(id))
        
        if instancia:
            instancia.num_guests_selected = int(invitados)
            instancia.guests_names = str(asistentes)
            instancia.answer = str(asistencia)
            
            instancia.save()
        

    return render(request = request, template_name = 'wedding_invitation_template.html')


def guests_table(request):
    if request.method == "GET":
        guests_query = models.Guests.objects.all()
    if request.method == "POST":
        eliminar = request.POST.get('boton-eliminar', None)
        models.Guests.objects.filter(id = eliminar).delete()
        guests_query = models.Guests.objects.all()
    return render(request, "guests_table.html", {'guests': guests_query})


def update_data(request, pk):
    '''
    
    '''
    if request.method == "POST":
        instance = models.Guests.objects.get(id = pk)
        form = forms.Guests_form(request.POST, instance = instance)
        if form.is_valid():
            form.save()
            return redirect('wedding_invitation_view')


def copy_data(request):
    if request.method == "GET":
        query = models.Guests.objects.all()
        print(query[0].num_guests_selected_char)
    return render(request, "x.html", {})

wedding/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"/>

        <title>Boda Janeth & Luis</title>
        <meta name="description" content="Boda Janeth & Luis">
        <meta name="author" content="SitePoint">

        <meta property="og:title" content="Boda Janeth & Luis">
        <meta property="og:type" content="website">

        {% comment %} <link rel="icon" href="/favicon.ico">
        <link rel="icon" href="/favicon.svg" type="image/svg+xml">
        <link rel="apple-touch-icon" href="/apple-touch-icon.png">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> {% endcomment %}

        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Charm&family=Italianno&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Italianno&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@700&display=swap" rel="stylesheet">
                <!------------------>
        
        <!-- Tailwind CDN -->
        <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
        <script defer src="https://unpkg.com/alpinejs@3.10.2/dist/cdn.min.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
        <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
        <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
        <link rel="stylesheet" href="https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/css/main.ad49aa9b.css" />
        <!------------------>

        <!-- JQUERY -->
        <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
        <!------------>
        <!-- Custom css & js -->
        {% block scripts %}{% endblock scripts %}
        <link rel = "stylesheet" href = "{% static 'wedding/css/style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" />

    </head>

    <body>
        <articule>
            <div>
                {% block content %}
                
                {% endblock content %}
            </div>
        </articule>

        {% block extrajs %}
        {% endblock extrajs %}
    </body>
</html>

wedding/templates/bride_form_template.html
{% extends "base.html" %}

{% load static %}
{% block content %}

    <h1 class = "add-invitados"> Agregar invitados </h1>
    <a class = "a-guestadata" href = "{% url 'wedding:guests_table' %}"> Tabla de invitados </a> 

    <form method = "POST" class = "form-bride">
        {% csrf_token %}
        {{form.identifier}}

        {{form.num_guests_assigned}}

        <button type = "submit" class = "button-reg h-12 min-w-[8rem] rounded-lg border-2 border-white-600 bg-white-500 text-white-50 shadow-lg hover:bg-white-600 focus:outline-none focus:ring focus:ring-white-600"> Registrar </button>
    </form>

{% endblock content %}

wedding/templates/guests_table.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    
    <!-- This is an example component -->
    <div class='flex min-h-screen items-center justify-center min-h-screen from-white-200 via-white-300 to-white-500 bg-gradient-to-br'>
        <div class="flex items-center justify-center min-h-[450px]">
            <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
                <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
                    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" class="py-3 px-6">Identificador</th>
                                <th scope="col" class="py-3 px-6">No. invitados</th>
                                
                                <th scope="col" class="py-3 px-6">Código</th>
                                <th scope="col" class="py-3 px-6">No. de invitados</th>
                                <th scope="col" class="py-3 px-6" style = "width: 35%;">Invitados</th>
                                
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for guest in guests %}
                                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                                    <td class="py-4 px-6">{{guest.identifier}}</td>
                                    <td class="py-4 px-6">{{guest.num_guests_assigned}}</td>
                                    
                                    <td class="py-4 px-6">{{guest.code}}</td>
                                    <td class="py-4 px-6">{{guest.num_guests_selected}}</td>
                                    <td class="py-4 px-6">{{guest.guests_names}}</td>
                                    <form method = "POST">
                                        {% csrf_token %}
                                        <td><button value = "{{guest.id}}" name = "boton-eliminar" type = "submit" > Eliminar </button></td>
                                    </form>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

wedding/templates/partial_results.html
{% comment %} {% for result in results  %} {% endcomment %}
<form method = "POST">
        {% comment %} <p> Buen día, {{result.identifier}} </p>
        <p> Se le han asignado {{result.num_guests_assigned}} invitados </p> {% endcomment %}
    {% comment %} {% endfor %} {% endcomment %}
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Registrar</button>
</form>

wedding/templates/wedding_invitation_template.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Bienvenida -->
    <section class = "fwh-slider fwh-slider--1">
        <p>
            <span> 02 | 03 | 24 </span>
        </p>
        <h1> J </h1>
        <h1> L </h1>

        <p id = "countdown"> </p>
    </section>

    <section class = "fwh-slider fwh-slider--2">
        <!-- Photo Grid -->
        <p> Con mucha ilusión, queremos que seas parte de nuestra boda. </p>
        <div class="row"> 
            <div class="column">
                <img src="/static/wedding/img/janeth/059.jpg" style="width:100%">
                <img src="/static/wedding/img/janeth/083.jpg" style="width:100%">
                <img src="/static/wedding/img/janeth/036.jpg" style="width:100%">
            </div>
            <div class="column">
                <img src="/static/wedding/img/janeth/090.jpg" style="width:100%">
                <img src="/static/wedding/img/janeth/076.jpg" style="width:100%">
            </div>  
            <div class="column">
                <img src="/static/wedding/img/janeth/029.jpg" style="width:100%">
                <img src="/static/wedding/img/janeth/067.jpg" style="width:100%">
            
                <img src="/static/wedding/img/janeth/063.jpg" style="width:100%">
            </div>
            <div class="column">
                <img src="/static/wedding/img/janeth/072.jpg" style="width:100%">
                <img src="/static/wedding/img/janeth/090.jpg" style="width:100%">
                <img src="/static/wedding/img/janeth/019.jpg" style="width:100%">
            </div>
        </div>
    </section>

    <section class = "fwh-slider fwh-slider--3">
        <!-- Itinerario -->
        <div class="container mx-auto w-full h-full">

            
            <div class="rectangulo">
                <p>Itinerario</p>
                <p>¡Esperamos que te la pases genial!</p>
            </div>

            <div class="top relative wrap overflow-hidden p-10">
                <div class="border-2-2 absolute border-opacity-20 border-gray-700 h-full border" style="left: 50%"></div>
                <div class="mb-8 flex justify-between items-center w-full right-timeline">
                    <div class="order-1 w-5/12"></div>
                    <div class="z-20 flex items-center order-1 bg-gray-800 shadow-xl w-2 h-2 rounded-full"></div>
                    <div class="order-1 w-5/12 px-6 py-4">
                        <p class="text-sm leading-snug tracking-wide text-gray-900 text-opacity-100 text-hora-ceremonia"> 04:00 PM </p>
                        <p class = "linea-1"> 
                            <span class = "ico-ceremonia"></span>
                        </p>
                        <h3 class="mb-3 text-gray-800 text-ceremonia">Ceremonia</h3>
                    </div>
                </div>
            
                <div class="mb-8 flex justify-between flex-row-reverse items-center w-full left-timeline">
                    <div class="order-1 w-5/12"></div>
                    <div class="z-20 flex items-center order-1 bg-gray-800 shadow-xl w-2 h-2 rounded-full"></div>
                    <div class="order-1 w-5/12 px-6 py-4">
                        <p class="text-sm leading-snug tracking-wide text-gray-900 text-opacity-100 text-hora-civil"> 06:30 PM </p>
                        <p class = "linea-2"> 
                            <span class = "ico-civil"></span>
                        </p>
                        <h3 class="mb-3 text-gray-800 text-civil">Civil</h3>
                    </div>
                </div>
                
                <div class="mb-8 flex justify-between items-center w-full right-timeline">
                    <div class="order-1 w-5/12"></div>
                    <div class="z-20 flex items-center order-1 bg-gray-800 shadow-xl w-2 h-2 rounded-full"></div>
                    <div class="order-1 w-5/12 px-6 py-4">
                        <p class="text-sm leading-snug tracking-wide text-gray-900 text-opacity-100 text-hora-recepcion"> 07:30 PM </p>
                        <p class = "linea-3"> 
                            <span class = "ico-recepcion"></span>
                        </p>
                        <h3 class="mb-3 text-gray-800 text-recepcion">Recepción</h3>
                    </div>
                </div>
            
                <div class="mb-8 flex justify-between flex-row-reverse items-center w-full left-timeline">
                    <div class="order-1 w-5/12"></div>
                    <div class="z-20 flex items-center order-1 bg-gray-800 shadow-xl w-2 h-2 rounded-full"></div>
                    <div class="order-1 w-5/12 px-6 py-4">
                        <p class="text-sm leading-snug tracking-wide text-gray-900 text-opacity-100 text-hora-cena"> 09:00 PM </p>
                        <p class = "linea-4"> 
                            <span class = "ico-cena"></span>
                        </p>
                        <h3 class="mb-3 text-gray-800 text-cena">Cena</h3>
                    </div>
                </div>
                <div class="mb-8 flex justify-between items-center w-full right-timeline">
                    <div class="order-1 w-5/12"></div>
                    <div class="z-20 flex items-center order-1 bg-gray-800 shadow-xl w-2 h-2 rounded-full"></div>
                    <div class="order-1 w-5/12 px-6 py-4">
                        <p class="text-sm leading-snug tracking-wide text-gray-900 text-opacity-100 text-hora-fiesta"> 10:00 PM </p>
                        <p class = "linea-5"> 
                            <span class = "ico-fiesta"></span>
                        </p>
                        <h3 class="mb-3 text-gray-800 text-fiesta">Que siga la fiesta!</h3>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class = "fwh-slider fwh-slider--4">
        <!-- Lugar -->
        <div class="rectangulo-2">
            <p>Ubicación</p>
        </div>

        <div>
            <p class = "txt-vertical-1"> CEREMONIA </p>
            <p class = "txt-direccion-1">4:00PM | Parroquia San José del Barrial</p>
            <a href = "https://goo.gl/maps/h21gEFkEokDRFozY8">
                <img class = "img-iglesia" src = "{% static 'wedding/img/parroquia-maps.png' %}" />
                <span class = "ico-iglesia-2"></span>
            </a>
        </div>

        <div>
            <p class = "txt-vertical-2"> RECEPCIÓN </p>
            
            <p class = "txt-direccion-2">7:30PM | Princess Wedding Garderns</p>
            <a href = "https://goo.gl/maps/8GeLSDZeL2kkWrs49">
                <img class = "img-salon" src = "{% static 'wedding/img/princess-maps.png' %}" />
                <span class = "ico-fiesta-2"></span>
            </a>
        </div>

    </section>

    <section class = "fwh-slider fwh-slider--5">
        <!-- Mesa de regalos / Vestimenta -->
        <div class="rectangulo-3">
            <p>Código de vestimenta</p>
        </div>

        <p class = "ico-vestimenta"></p>
        <p class = "text-formal"> Formal </p>
        <p class = "text-vestimenta"> ¡La idea es que te sientas cómodo(a)! </p>
        <p class = "text-ejemplo"> Fiesta en jardín </p>

        <div class="rectangulo-4">
            <p>Mesa de regalos</p>
        </div>

        <diV>
            <a href = "https://www.amazon.com.mx/wedding/janeth-guadalupe-bustos-gonzález-luis-jesus-martinez-aguilar-santiago-nuevo-leoacuten-march-2024/registry/37LV3ZJH8CFUN">
                <span class = "ico-amazon"></span>
            </a>
            
            <span class = "ico-sobre"></span>
        </div>

        

    </section>

    <section class = "fwh-slider fwh-slider--6">
        <!-- Formulario -->
        <div class="rectangulo-5">
            <p>Confirmación de asistencia</p>
        </div>

        <div>
            <form class = "searchForm">
                <label id = "labelInvitacion" class = "label-form"> Escribir el código de invitación </label>
                <div class="flex gap-4">
                    <input id = "code" class="h-18 min-w-[20rem] rounded-lg border-white-500 indent-4 text-white-900 shadow-lg focus:outline-none focus:ring focus:ring-white-600" type="text" placeholder="Código de invitación" />
                </div>
            </br>
                <div>
                    <button type = "button" id = "code_submit" onclick = "myFunction()" class="button-buscar h-12 min-w-[8rem] rounded-lg border-2 border-white-600 bg-white-500 text-white-50 shadow-lg hover:bg-white-600 focus:outline-none focus:ring focus:ring-white-600">Buscar</button>
                </div>
            </form>

            <label id = "invitados" class = "label-form1">  </label>
            <label id = "no-codigo" class = "label-form-no">  </label>
            </br>
            <label id = "intento" class = "label-form-intento">  </label>
            <label id = "asistentes" class = "label-form2">  </label>

            <form class = "searchForm" method = "POST">
                {% csrf_token %}
                <div class="flex gap-4">
                    <input  id = "input-invitados"  style = "display: none;" name = "invitados" class="h-18 min-w-[20rem] rounded-lg border-white-500 indent-4 text-white-900 shadow-lg focus:outline-none focus:ring focus:ring-white-600 input-invitados" type="text" placeholder="Cantidad de asistentes" />
                </div>
                <div class="flex gap-4">
                    <input id = "input-asistentes"  style = "display: none;" name = "asistentes" class="h-18 min-w-[20rem] rounded-lg border-white-500 indent-4 text-white-900 shadow-lg focus:outline-none focus:ring focus:ring-white-600 input-asistentes" type="text" placeholder="Nombre de asistentes" />
                </div>

                <div class="flex gap-4">
                    <input name = "id"  id = "idInput" style = "display: none;" type="text" placeholder="" />
                </div>

                <label id = "label-asistencia" class = "label-form3" style = "display: none;"> ¿Nos acompañarás? </label>
                <label id = "label-noasistencia" class = "label-form4" style = "display: none;"> No se asistirá </label>
                <div class="flex gap-4">
                    <select id = "select-asistencia" name = "asistencia"  class = "selectAsistencia" style = "display: none;" onchange = "mostrarCampos()">
                        <option>-----------</option>
                        <option>Sí asistiré</option>
                        <option>No asistiré</option>
                    </select>
                </div>

                <button  id = "button-registrar" style = "display: none;" type = "submit" class="h-12 min-w-[8rem] rounded-lg border-2 border-white-600 bg-white-500 text-white-50 shadow-lg hover:bg-white-600 focus:outline-none focus:ring focus:ring-white-600 button-registrar">Registrar</button>
            </form>
        </div>

    </section>

    <section class = "fwh-slider fwh-slider--7">
        <p class = "agradecimiento"> Muchas gracias por su tiempo, los esperamos </p>
    </section>


{% endblock content %}

{% block extrajs %}
    <script src = "{% static 'wedding/js/countdown.js' %}"> </script>
    <script src = "{% static 'wedding/js/slider.js' %}"> </script>
    <script src = "{% static 'wedding/js/index.js' %}"> </script>
{% endblock extrajs %}

wedding/templates/x.html
{% extends "base.html" %}

{% load static %}
{% block content %}

{% endblock content %}